php_admin_value[session.gc_probability] = 1
php_admin_value[session.gc_divisor] = 500
php_admin_value[upload_max_filesize] = 1G
php_admin_value[post_max_size] = 1G
php_admin_value[memory_limit] = 512M
