#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE THE REDIS DATABASE
#=================================================
ynh_script_progression "Removing Redis database..."

ynh_redis_remove_db "$redis_db"

ynh_config_remove_nginx

ynh_config_remove_phpfpm

ynh_safe_rm "/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
